import React from "react";
import { connect } from "react-redux";
import * as courseActions from "../../redux/actions/courseActions";
import PropTypes from "prop-types";
<<<<<<< HEAD
import { bindActionCreators } from "redux";

class CoursesPage extends React.Component {
  render() {
    return (
      // wrapping in a JSX fragment so that there is one top-level component (required for JSX)
      <>
        <h2>Courses</h2>
        {this.props.courses.map(course => (
          <div key={course.title}>{course.title}</div>
        ))}
      </>
=======

class CoursesPage extends React.Component {
  state = {
    course: {
      title: ""
    }
  };

  /**
   * We update this object's state's course object with a new title as the user types it in.
   * course is equal to course: course i.e. the object shorthand syntax
   * @param {Object} event The event generated by the input element and automatically passed in.
   */
  handleChange = event => {
    const course = { ...this.state.course, title: event.target.value };
    this.setState({ course: course });
  };

  handleSubmit = event => {
    event.preventDefault();
    this.props.createCourse(this.state.course);
    //alert(this.state.course.title);
  };

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <h2>Courses</h2>
        <h3>Add Course</h3>
        <input
          type="text"
          onChange={this.handleChange}
          value={this.state.course.title}
        />

        <input type="submit" value="Save" />
        {this.props.courses.map(course => (
          <div key={course.title}>{course.title}</div>
        ))}
      </form>
>>>>>>> master
    );
  }
}

CoursesPage.propTypes = {
  courses: PropTypes.array.isRequired,
<<<<<<< HEAD
  actions: PropTypes.func.isRequired
=======
  createCourse: PropTypes.func.isRequired
>>>>>>> master
};

function mapStateToProps(state) {
  return {
    courses: state.courses
  };
}

function mapDispatchToProps(dispatch) {
  return {
<<<<<<< HEAD
    actions: bindActionCreators(courseActions, dispatch)
=======
    createCourse: course => dispatch(courseActions.createCourse(course))
>>>>>>> master
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CoursesPage);
